import type { FlashcardDefinition } from "@/types/flashcard";

export const deloitteQuantumInsightsFlashcards: readonly FlashcardDefinition[] = [
  {
    id: "dqi-fc-1",
    topicId: "deloitte-quantum-insights",
    front: "Deloitte調査で量子コンピューティングに投資した企業の価値実感率は？",
    back: "76%が「大きな、または非常に大きな価値を得ている」と回答。投資率は25%で前年比3倍増。（Quantum Computing Futures, 2025）",
    tags: ["market", "statistics"],
    relatedLessonId: "dqi-lesson-1",
  },
  {
    id: "dqi-fc-2",
    topicId: "deloitte-quantum-insights",
    front: "Deloitteが予測する2040年の量子技術の経済価値は？",
    back: "約120兆円。AIの現在の社会的インパクトに匹敵する規模。2030年の市場規模は約650億ドル（CAGR 56%）。",
    tags: ["market", "forecast"],
    relatedLessonId: "dqi-lesson-1",
  },
  {
    id: "dqi-fc-3",
    topicId: "deloitte-quantum-insights",
    front: "Quantum Harborプロジェクトとは？",
    back: "デロイトトーマツが2024年1月に始動した量子産業創出プロジェクト。技術研究・エコシステム形成・産業支援の3本柱。グローバル700名、日本50名の量子専門チーム。",
    tags: ["deloitte-japan", "organization"],
    relatedLessonId: "dqi-lesson-1",
  },
  {
    id: "dqi-fc-4",
    topicId: "deloitte-quantum-insights",
    front: "Q-Day / Y2Qとは？",
    back: "CRQCが現行暗号を破れるようになる日。DeloitteはY2Kとの対比で「Y2Q」と命名。「影響はY2Kより広範だが、日付が不明」。コンセンサスは5〜10年以内。",
    tags: ["timeline", "threat"],
    relatedLessonId: "dqi-lesson-2",
  },
  {
    id: "dqi-fc-5",
    topicId: "deloitte-quantum-insights",
    front: "Deloitteの4シナリオを列挙せよ",
    back: "1. SURPRISE（量子早期×人材未発達）→最もリスク高\n2. QUANDARY（両方遅延）→量子の冬\n3. EXPLOSION（両方発展）→量子優位確認\n4. LEAP（量子遅延×人材発達）→インスパイアドで価値創出",
    tags: ["scenario", "strategy"],
    relatedLessonId: "dqi-lesson-2",
  },
  {
    id: "dqi-fc-6",
    topicId: "deloitte-quantum-insights",
    front: "HNDL攻撃についてDeloitteの見解は？",
    back: "「将来の脅威」ではなく「今日すでに進行中の脅威」。攻撃者は比較的容易かつ低コストで暗号化データを大量に収集し、CRQCの成熟を待っている。",
    tags: ["threat", "hndl"],
    relatedLessonId: "dqi-lesson-3",
  },
  {
    id: "dqi-fc-7",
    topicId: "deloitte-quantum-insights",
    front: "Deloitte PQCマイグレーション5ステップは？",
    back: "1. Discover（暗号インベントリ）\n2. Assess（リスク評価・優先順位付け）\n3. Govern（ガバナンス確立）\n4. Migrate（PQC実装・テスト）\n5. Sustain（クリプトアジリティ運用）",
    tags: ["migration", "framework"],
    relatedLessonId: "dqi-lesson-3",
  },
  {
    id: "dqi-fc-8",
    topicId: "deloitte-quantum-insights",
    front: "PQC移行のY2Kとの比較は？",
    back: "「Y2Kの10倍の準備が必要」（Deloitte/Quantropi）。SHA1→SHA2でさえ数年を要した。NIST移行期限は2030年。NISTのPQC標準は2024年8月に公開済み。",
    tags: ["migration", "scale"],
    relatedLessonId: "dqi-lesson-3",
  },
  {
    id: "dqi-fc-9",
    topicId: "deloitte-quantum-insights",
    front: "三菱ケミカル×Classiq×デロイトの実証成果は？",
    back: "有機EL材料探索で量子回路を最大97%圧縮。Classiq（イスラエル）の回路最適化技術を活用。2024年12月発表。",
    tags: ["use-case", "japan"],
    relatedLessonId: "dqi-lesson-4",
  },
  {
    id: "dqi-fc-10",
    topicId: "deloitte-quantum-insights",
    front: "量子×AI融合の2大ブレークスルー領域は？",
    back: "1. データ拡張: 量子乱数による超高精度データ水増し→不正検知・異常検知に活用\n2. 学習超効率化: 量子アルゴリズムでML効率化→省ニューロン・省電力",
    tags: ["ai", "convergence"],
    relatedLessonId: "dqi-lesson-4",
  },
  {
    id: "dqi-fc-11",
    topicId: "deloitte-quantum-insights",
    front: "WEF/Deloitte Quantum Readiness Toolkitの5原則は？",
    back: "1. 教育（リーダー＋運用チーム）\n2. ガバナンス（構造への組み込み）\n3. テクノロジー（量子安全技術の選定）\n4. 協力体制（組織横断・業界横断）\n5. 即時行動（複数年かかるため今始める）",
    tags: ["readiness", "framework"],
    relatedLessonId: "dqi-lesson-5",
  },
  {
    id: "dqi-fc-12",
    topicId: "deloitte-quantum-insights",
    front: "デロイトが日本企業に警告する3つのリスクは？",
    back: "1. ハードウェアリソース枯渇（2030年頃の供給不足）\n2. 人材育成のリードタイム不足（3〜5年必要）\n3. パラダイムシフト対応の遅れ（クラウド・AIの二の舞）\n→「10年後の勝者は、今決まる」",
    tags: ["japan", "risk"],
    relatedLessonId: "dqi-lesson-5",
  },
] as const satisfies readonly FlashcardDefinition[];
