import type { FlashcardDefinition } from "@/types/flashcard";

export const quantumLiteracyTrainingFlashcards: readonly FlashcardDefinition[] = [
  {
    id: "ql-train-fc1",
    topicId: "quantum-literacy-training",
    front: "経営層向け量子ブリーフィングの逆ピラミッド構造とは？",
    back: "結論（何をすべきか）→ 理由（なぜ今か）→ 背景（技術的根拠）の順で構成。\n\n経営層が最も重要な情報を最初に受け取れる。詳細に興味があれば深掘りし、そうでなければ結論と理由で完結。\n\n30分ブリーフィング例: オープニング(5分) → 脅威(7分) → 機会(6分) → アクション(7分) → Q&A(5分)",
    tags: ["training", "executive", "structure"],
    relatedLessonId: "ql-train-lesson1",
  },
  {
    id: "ql-train-fc2",
    topicId: "quantum-literacy-training",
    front: "経営層への説明の3つの鉄則は？",
    back: "鉄則1: 具体的な数字で語る — 「リスクが高い」ではなく「暗号資産の73%が量子脆弱」\n鉄則2: 身近なアナロジーを使う — 正確さより直感的理解を優先\n鉄則3: 行動可能な選択肢を提示する — 「検討してください」ではなく「A:500万円/2ヶ月、B:来年度、C:様子見」の3択",
    tags: ["training", "executive", "presentation"],
    relatedLessonId: "ql-train-lesson1",
  },
  {
    id: "ql-train-fc3",
    topicId: "quantum-literacy-training",
    front: "研修後フォローアップの設計は？",
    back: "単発イベントではなく継続プログラムとして設計:\n・月次: 1ページニュースレター（業界動向 + 自社への影響）\n・四半期: 30分アップデートセッション\n・年次: フォローアップ研修（最新動向反映）\n\nニュースレターは「新情報」と「前回の復習」を半分ずつ。量子リスクを経営アジェンダに定着させる。",
    tags: ["training", "follow-up", "continuity"],
    relatedLessonId: "ql-train-lesson1",
  },
  {
    id: "ql-train-fc4",
    topicId: "quantum-literacy-training",
    front: "3段階の深度による説明設計とは？",
    back: "深度1（5分）: 一言で本質を伝える — エレベーターピッチ\n深度2（30分）: 仕組みの概要を理解させる — 比喩と図表で\n深度3（2時間）: 技術的な議論に参加できるレベル — 原理と実装\n\n聴衆のニーズ（経営層→深度1-2、技術者→深度3）に応じて選択。",
    tags: ["training", "explanation", "depth"],
    relatedLessonId: "ql-train-lesson2",
  },
  {
    id: "ql-train-fc5",
    topicId: "quantum-literacy-training",
    front: "量子技術の主要アナロジーマッピングを3つ挙げよ。",
    back: "1. 量子ビットの重ね合わせ → 回転中のコイン（表と裏の可能性が共存、観測で確定）\n2. RSA暗号の解読 → 掛け算の逆算（通常は宇宙の年齢級、Shorで数時間）\n3. 格子暗号 → 高次元空間の迷路（量子でも効率的な解法が見つかっていない）",
    tags: ["training", "analogy", "explanation"],
    relatedLessonId: "ql-train-lesson2",
  },
  {
    id: "ql-train-fc6",
    topicId: "quantum-literacy-training",
    front: "技術説明で避けるべき3つの落とし穴は？",
    back: "1. 過度な単純化: 「量子はすべてを高速化」は誤り。特定問題でのみ優位性\n2. 専門用語の乱用: エンタングルメント等を説明なく使うと5分で離脱\n3. 時期の誤認: 「まだ先」も「もうすぐ」も不正確。HNDL攻撃は今日始まっているが、汎用量子コンピュータは10-15年先",
    tags: ["training", "pitfalls", "explanation"],
    relatedLessonId: "ql-train-lesson2",
  },
  {
    id: "ql-train-fc7",
    topicId: "quantum-literacy-training",
    front: "3層カリキュラムの各Tierの対象・形式・目的は？",
    back: "Tier 1: 全社員 / eラーニング30分 / 量子脅威の存在認識\nTier 2: 管理職・IT部門 / ワークショップ半日 / PQC移行の理解と自部門の対応計画\nTier 3: 技術者 / ハンズオン1日 / PQCアルゴリズムの技術理解とハイブリッド実装\n\n職務関連性が基本原則。教養ではなく業務上のリスク対応として位置づける。",
    tags: ["training", "curriculum", "design"],
    relatedLessonId: "ql-train-lesson3",
  },
  {
    id: "ql-train-fc8",
    topicId: "quantum-literacy-training",
    front: "カークパトリックモデルの4段階を説明せよ。",
    back: "Level 1: 反応 — 研修直後のアンケート（満足度、難易度）\nLevel 2: 学習 — 研修前後の理解度テスト（知識のスコア化）\nLevel 3: 行動 — 3ヶ月後の行動変容（棚卸し協力度、ポリシー遵守率）\nLevel 4: 成果 — 6ヶ月後のビジネスインパクト（PQC移行進捗、インシデント減少）\n\n多くの研修はLevel 1で止まるが、Level 3-4まで追跡することが研修の価値証明に不可欠。",
    tags: ["training", "measurement", "kirkpatrick"],
    relatedLessonId: "ql-train-lesson3",
  },
  {
    id: "ql-train-fc9",
    topicId: "quantum-literacy-training",
    front: "研修プログラムの差別化と価格設計のポイントは？",
    back: "差別化:\n・「一般教養」ではなく「御社の棚卸しデータに基づくリスク研修」\n・棚卸しデータを研修素材に活用 → 自分ごと感を高める\n\n価格設計:\n・Tier 1: 1人あたり月額課金\n・Tier 2-3: 研修回数ベース\n・カスタマイズ費用は別途\n\nリピート: 年次更新コンテンツを継続契約として提案（量子技術の変化の速さが正当性の根拠）",
    tags: ["training", "pricing", "differentiation"],
    relatedLessonId: "ql-train-lesson3",
  },
  {
    id: "ql-train-fc10",
    topicId: "quantum-literacy-training",
    front: "研修の成功指標（理解度確認）の最良の方法は？",
    back: "「聴衆が自分の言葉で他者に説明できるか」\n\n研修の最後に「今日学んだことを、自部門のメンバーにどう説明しますか？」と問いかけ、参加者自身の言葉で要約させる。\n\n真の理解は、他者への説明能力で測定できる。テストのスコアだけでは表面的な記憶と本質的な理解を区別できない。",
    tags: ["training", "assessment", "understanding"],
    relatedLessonId: "ql-train-lesson2",
  },
] as const satisfies readonly FlashcardDefinition[];
